version: 2.1
orbs:
  s3: ngs/s3-deploy@0.0.1
jobs:
  build-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/
  build-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel7
      - build-rhel8
      - test-rhel7:
          requires:
            - build-rhel7
      - test-rhel8:
          requires:
            - build-rhel8
      - s3/deploy:
          requires:
            - test-rhel7
          filters:
            branches:
              only: master
          workspace: .
          artifacts: dist
          bucket: fmi-smartmet-cicd-beta
          cloudfront_distribution_id: E1N8O8NLCHFHF2
